In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [82]:
animals = ['dog', 'cat', 'bird', 'horse']
animals

['dog', 'cat', 'bird', 'horse']

In [100]:
locations = ["golden gate bridge", "empire state building", "pacific ocean", "mt denali"]
# ca, ny, wc, ak = locations

In [104]:
# for index, value in enumerate(locations):
#     print value, " has index ", index

golden gate bridge  has index  0
empire state building  has index  1
pacific ocean  has index  2
mt denali  has index  3


'mt denali'

In [114]:
crap_data = [
    ['0.234.M.$34--', 2, 3,4, 5, 6],
 ['0.234.234.S.$23--', 2, 3,4, 5, 6],
['0.*(.234.BD.$123--', 2, 3,4, 5, 6],
['0.234.E.$12--', 2, 3,4, 5, 6]
]

for row in crap_data:
    print row[0].split('.')



['0', '234', 'M', '$34--']
['0', '234', '234', 'S', '$23--']
['0', '*(', '234', 'BD', '$123--']
['0', '234', 'E', '$12--']


In [81]:
columns  = ["col1", "col2", "col3", "col4"]
list_data = [[2,4,5,6], [33,33,22,55], [33,22,44,66], [22,33,23,23], [555,55,555,5]]
        
transformed = {}

for column_index, column_name in enumerate(columns):
    
    print "Getting column index: ", column_index, "column name:", column_name

    for row in list_data:
        # Do we have data for this column yet?
        if column_index in transformed.keys():
            transformed[column_name].append(row[column_index])
        # If we don't have column data (first time we see this)
        else:
            transformed[column_name] = [row[column_index]]
            
transformed

Getting column index:  0 column name: col1
Getting column index:  1 column name: col2
Getting column index:  2 column name: col3
Getting column index:  3 column name: col4


{'col1': [555], 'col2': [55], 'col3': [555], 'col4': [5]}

In [80]:
for index, row in transformed.items():
    
    rounded = [round(value) for value in row]
    print rounded

[5.0]
[55.0]
[555.0]
[555.0]


In [61]:
my_vect = [33.22234234234, 44.22234234, 1.0923423423499, 3.2222342349, 9.444]
["%.6f" % val for val in my_vect]

['33.222342', '44.222342', '1.092342', '3.222234', '9.444000']

ImportError: No module named pandas

In [15]:
\

array([5, 4, 3, 2, 1])

In [16]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [17]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [14]:
np.dot(a, b)

35