In [2]:
import numpy as np

In [14]:
a =  ['i0', 'i1']
vector = np.array(a)
vector

array(['i0', 'i1'], 
      dtype='|S2')

In [15]:
mtx_tbt = np.array([a, a])
mtx_tbt

array([['i0', 'i1'],
       ['i0', 'i1']], 
      dtype='|S2')

In [19]:
b = ['i0', 'i1', 'i2']

mtx_thbth = np.array([b,b,b])

mtx_thbth

array([['i0', 'i1', 'i2'],
       ['i0', 'i1', 'i2'],
       ['i0', 'i1', 'i2']], 
      dtype='|S2')

In [32]:
c = ['i0', 'i1', 'i2','i3', 'i4', 'i5','i6', 'i7',]

mtx_fourbyeight = np.array([c,c,c,c])


for i, array in enumerate(mtx_fourbyeight):
    print "row", i+1,":", array

print mtx_fourbyeight.shape

row 1 : ['i0' 'i1' 'i2' 'i3' 'i4' 'i5' 'i6' 'i7']
row 2 : ['i0' 'i1' 'i2' 'i3' 'i4' 'i5' 'i6' 'i7']
row 3 : ['i0' 'i1' 'i2' 'i3' 'i4' 'i5' 'i6' 'i7']
row 4 : ['i0' 'i1' 'i2' 'i3' 'i4' 'i5' 'i6' 'i7']
(4, 8)


In [5]:
a = [ 1,2,3,4,5 ]
b = [ 5,4,3,2,1 ]

# Adding and Subtracting Matricies

## Adding 

a[0] + b[0], a[1] + b[1], ..., a[4] + b[4]

## Subtracting 
a[0] - b[0], a[1] - b[1], ..., a[4] - b[4]

In [6]:
# Adding through numpy

np.add(a,b)

array([6, 6, 6, 6, 6])

## Exercises:


In [7]:
# 1. Add
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]

np.add(a, b)

array([-5, -3, -1,  1,  3,  5])

In [8]:
# 2. Subtract
a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]

np.subtract(a,b)

array([ 5,  3,  1, -1, -3, -5])

In [9]:
# 3. Subtract
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]

np.subtract(a, b)

array([ 702.       , -300.33     ,  146.22     , -426.3000003,
          7.3234   ,   -4.234    ])

In [23]:
# 4. Subtract

a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]

b_mod = []
for x in b:
    if (type(x) == (str)) : # If item is a string
        x = 0 # assign item as value 0
        b_mod.append(x) # append to list
    else: # If float or int
        b_mod.append(x) # append to list

for difference in np.subtract(a, b_mod):
    print difference

-702.0
300.33
-146.22
426.3000003
-5.3234
-45.0


# Array Practice
## 2D Array

In [25]:
arr1 = np.array([ 8 , 6 , 7.53 , .09 ])
arr2 = np.array([9, 7, 8.530000000000001, 1.09])

In [26]:
# Add
np.add(arr1,arr2)

array([ 17.  ,  13.  ,  16.06,   1.18])

In [27]:
# Subtract 
np.subtract(arr1,arr2)

array([-1., -1., -1., -1.])

In [28]:
# Dot
np.dot(arr1,arr2)

178.32900000000001

## 3D Array

In [37]:
# Create a 3 dimensional array
#1D = []
#2D =[[],[]]
"""3D =[
    [[],[]],
    [[],[]],
    [[],[]]
]"""

arr_3 =[
    [['a'],['b']],
    [['c'],['d']],
    [['e'],['f']]
]

arr_3D = np.array(arr_3)

arr_3D

array([[['a'],
        ['b']],

       [['c'],
        ['d']],

       [['e'],
        ['f']]], 
      dtype='|S1')